site_name: discord-bot-template
repo_name: GriceTurrble/discord-bot-template
repo_url: https://github.com/griceturrble/discord-bot-template
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.footer
    - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

copyright: Copyright &copy; 2024 - present Galen Rice

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/griceturrble/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/griceturrble.bsky.social

plugins:
  - search

nav:
  - index.md
  - getting_started.md
  - explore.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.keys
  - pymdownx.superfences
  - toc:
      permalink: "#"
